/*
    Theengs - Decode things and devices
    Copyright: (c) Florian ROBERT

    This file is part of Theengs.

    Theengs is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    Theengs is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#include "Entitlement.h"
#include "EntitlementEras.h"
#include "ProvenanceStore.h"

#include <QCoreApplication>
#include <QSettings>
#include <QDateTime>
#include <QString>
#include <QDebug>

#if defined(Q_OS_ANDROID)
#include <QJniObject>
#include <QJniEnvironment>
#endif

namespace {

// Best-effort per-platform build integer. Used as a provenance breadcrumb
// only; not load-bearing for the current grant decision (the grant is
// unconditional — this binary is the paid build).
//
// Android: BuildConfig.VERSION_CODE — a primitive `int` static field
// generated by Gradle into the app's package namespace (com.theengs.app).
// The build.gradle in this repo sets versionCode = seconds-since-epoch at
// build time, so this integer is monotonically increasing per build and
// can later be compared against the boundaries in EntitlementEras.
//
// iOS/desktop: recorded as 0. On iOS, the Apple-held CFBundleVersion is
// available later via AppTransaction.originalAppVersion at decision time,
// so pre-recording it here would only be a breadcrumb.
int currentBuildNumber()
{
#if defined(Q_OS_ANDROID)
    const jint code = QJniObject::getStaticField<jint>(
        "com/theengs/app/BuildConfig", "VERSION_CODE");
    QJniEnvironment env;
    if (env.checkAndClearExceptions())
    {
        qWarning() << "Entitlement: failed to read BuildConfig.VERSION_CODE; recording 0";
        return 0;
    }
    return static_cast<int>(code);
#else
    return 0;
#endif
}

} // namespace

namespace Entitlement
{

void stampOnceAtStartup()
{
    // Same QSettings keying as SettingsManager so the file is shared (and
    // therefore in the same Android Auto-Backup set).
    QSettings settings(QCoreApplication::organizationName(),
                       QCoreApplication::applicationName());

    const auto &era = EntitlementEras::currentEraForStampRelease();
    const qint64 nowMs = QDateTime::currentMSecsSinceEpoch();
    const int build = currentBuildNumber();

    ProvenanceStore::stampIfFirstLaunch(
        settings,
        nowMs,
        build,
        QString::fromLatin1(era.id),
        QStringLiteral("GF_ANDROID_STAMP"));
}

} // namespace Entitlement
