name: Create and publish documentation
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  documentation:
    runs-on: ubuntu-latest
    name: Create the documentation and deploy it to GitHub Pages
    steps:
      - uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "20.x"
      - name: Install build dependencies
        run: npm install
      - name: Build documentation
        run: npm run docs:build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist
          cname: app.theengs.io
